using System.Collections.Generic;
using UnityEngine;

public static class TypeEffectiveness
{
    public static Dictionary<(ElementType attacker, ElementType defender), float> chart = new()
    {
        { (ElementType.Normal, ElementType.Normal), 1f },
        { (ElementType.Normal, ElementType.Fire), 1f },
        { (ElementType.Normal, ElementType.Water), 1f },
        { (ElementType.Normal, ElementType.Electric), 1f },
        { (ElementType.Normal, ElementType.Grass), 1f },
        { (ElementType.Normal, ElementType.Ice), 1f },
        { (ElementType.Normal, ElementType.Fighting), 1f },
        { (ElementType.Normal, ElementType.Poison), 1f },
        { (ElementType.Normal, ElementType.Ground), 1f },
        { (ElementType.Normal, ElementType.Flying), 1f },
        { (ElementType.Normal, ElementType.Psychic), 1f },
        { (ElementType.Normal, ElementType.Bug), 1f },
        { (ElementType.Normal, ElementType.Rock), 0.5f },
        { (ElementType.Normal, ElementType.Ghost), 0.5f },
        { (ElementType.Normal, ElementType.Dragon), 1f },
        { (ElementType.Fire, ElementType.Normal), 1f },
        { (ElementType.Fire, ElementType.Fire), 1f },
        { (ElementType.Fire, ElementType.Water), 0.5f },
        { (ElementType.Fire, ElementType.Electric), 1f },
        { (ElementType.Fire, ElementType.Grass), 2f },
        { (ElementType.Fire, ElementType.Ice), 1f },
        { (ElementType.Fire, ElementType.Fighting), 1f },
        { (ElementType.Fire, ElementType.Poison), 1f },
        { (ElementType.Fire, ElementType.Ground), 1f },
        { (ElementType.Fire, ElementType.Flying), 1f },
        { (ElementType.Fire, ElementType.Psychic), 1f },
        { (ElementType.Fire, ElementType.Bug), 1f },
        { (ElementType.Fire, ElementType.Rock), 0.5f },
        { (ElementType.Fire, ElementType.Ghost), 1f },
        { (ElementType.Fire, ElementType.Dragon), 1f },
        { (ElementType.Water, ElementType.Normal), 1f },
        { (ElementType.Water, ElementType.Fire), 1f },
        { (ElementType.Water, ElementType.Water), 1f },
        { (ElementType.Water, ElementType.Electric), 1f },
        { (ElementType.Water, ElementType.Grass), 0.5f },
        { (ElementType.Water, ElementType.Ice), 1f },
        { (ElementType.Water, ElementType.Fighting), 1f },
        { (ElementType.Water, ElementType.Poison), 1f },
        { (ElementType.Water, ElementType.Ground), 1f },
        { (ElementType.Water, ElementType.Flying), 1f },
        { (ElementType.Water, ElementType.Psychic), 1f },
        { (ElementType.Water, ElementType.Bug), 1f },
        { (ElementType.Water, ElementType.Rock), 1f },
        { (ElementType.Water, ElementType.Ghost), 1f },
        { (ElementType.Water, ElementType.Dragon), 1f },
        { (ElementType.Electric, ElementType.Normal), 1f },
        { (ElementType.Electric, ElementType.Fire), 1f },
        { (ElementType.Electric, ElementType.Water), 1f },
        { (ElementType.Electric, ElementType.Electric), 1f },
        { (ElementType.Electric, ElementType.Grass), 1f },
        { (ElementType.Electric, ElementType.Ice), 1f },
        { (ElementType.Electric, ElementType.Fighting), 1f },
        { (ElementType.Electric, ElementType.Poison), 1f },
        { (ElementType.Electric, ElementType.Ground), 0.5f },
        { (ElementType.Electric, ElementType.Flying), 1f },
        { (ElementType.Electric, ElementType.Psychic), 1f },
        { (ElementType.Electric, ElementType.Bug), 1f },
        { (ElementType.Electric, ElementType.Rock), 1f },
        { (ElementType.Electric, ElementType.Ghost), 1f },
        { (ElementType.Electric, ElementType.Dragon), 1f },
        { (ElementType.Grass, ElementType.Normal), 1f },
        { (ElementType.Grass, ElementType.Fire), 0.5f },
        { (ElementType.Grass, ElementType.Water), 1f },
        { (ElementType.Grass, ElementType.Electric), 1f },
        { (ElementType.Grass, ElementType.Grass), 1f },
        { (ElementType.Grass, ElementType.Ice), 1f },
        { (ElementType.Grass, ElementType.Fighting), 1f },
        { (ElementType.Grass, ElementType.Poison), 0.5f },
        { (ElementType.Grass, ElementType.Ground), 2f },
        { (ElementType.Grass, ElementType.Flying), 1f },
        { (ElementType.Grass, ElementType.Psychic), 1f },
        { (ElementType.Grass, ElementType.Bug), 1f },
        { (ElementType.Grass, ElementType.Rock), 1f },
        { (ElementType.Grass, ElementType.Ghost), 1f },
        { (ElementType.Grass, ElementType.Dragon), 1f },
        { (ElementType.Ice, ElementType.Normal), 1f },
        { (ElementType.Ice, ElementType.Fire), 1f },
        { (ElementType.Ice, ElementType.Water), 1f },
        { (ElementType.Ice, ElementType.Electric), 1f },
        { (ElementType.Ice, ElementType.Grass), 1f },
        { (ElementType.Ice, ElementType.Ice), 1f },
        { (ElementType.Ice, ElementType.Fighting), 1f },
        { (ElementType.Ice, ElementType.Poison), 1f },
        { (ElementType.Ice, ElementType.Ground), 1f },
        { (ElementType.Ice, ElementType.Flying), 1f },
        { (ElementType.Ice, ElementType.Psychic), 1f },
        { (ElementType.Ice, ElementType.Bug), 1f },
        { (ElementType.Ice, ElementType.Rock), 0.5f },
        { (ElementType.Ice, ElementType.Ghost), 1f },
        { (ElementType.Ice, ElementType.Dragon), 2f },
        { (ElementType.Fighting, ElementType.Normal), 1f },
        { (ElementType.Fighting, ElementType.Fire), 1f },
        { (ElementType.Fighting, ElementType.Water), 1f },
        { (ElementType.Fighting, ElementType.Electric), 1f },
        { (ElementType.Fighting, ElementType.Grass), 1f },
        { (ElementType.Fighting, ElementType.Ice), 1f },
        { (ElementType.Fighting, ElementType.Fighting), 1f },
        { (ElementType.Fighting, ElementType.Poison), 1f },
        { (ElementType.Fighting, ElementType.Ground), 1f },
        { (ElementType.Fighting, ElementType.Flying), 0.5f },
        { (ElementType.Fighting, ElementType.Psychic), 0.5f },
        { (ElementType.Fighting, ElementType.Bug), 1f },
        { (ElementType.Fighting, ElementType.Rock), 2f },
        { (ElementType.Fighting, ElementType.Ghost), 0.5f },
        { (ElementType.Fighting, ElementType.Dragon), 1f },
        { (ElementType.Poison, ElementType.Normal), 1f },
        { (ElementType.Poison, ElementType.Fire), 1f },
        { (ElementType.Poison, ElementType.Water), 1f },
        { (ElementType.Poison, ElementType.Electric), 1f },
        { (ElementType.Poison, ElementType.Grass), 1f },
        { (ElementType.Poison, ElementType.Ice), 1f },
        { (ElementType.Poison, ElementType.Fighting), 1f },
        { (ElementType.Poison, ElementType.Poison), 1f },
        { (ElementType.Poison, ElementType.Ground), 1f },
        { (ElementType.Poison, ElementType.Flying), 1f },
        { (ElementType.Poison, ElementType.Psychic), 1f },
        { (ElementType.Poison, ElementType.Bug), 1f },
        { (ElementType.Poison, ElementType.Rock), 0.5f },
        { (ElementType.Poison, ElementType.Ghost), 1f },
        { (ElementType.Poison, ElementType.Dragon), 1f },
        { (ElementType.Ground, ElementType.Normal), 1f },
        { (ElementType.Ground, ElementType.Fire), 1f },
        { (ElementType.Ground, ElementType.Water), 1f },
        { (ElementType.Ground, ElementType.Electric), 2f },
        { (ElementType.Ground, ElementType.Grass), 0.5f },
        { (ElementType.Ground, ElementType.Ice), 1f },
        { (ElementType.Ground, ElementType.Fighting), 1f },
        { (ElementType.Ground, ElementType.Poison), 1f },
        { (ElementType.Ground, ElementType.Ground), 1f },
        { (ElementType.Ground, ElementType.Flying), 1f },
        { (ElementType.Ground, ElementType.Psychic), 1f },
        { (ElementType.Ground, ElementType.Bug), 1f },
        { (ElementType.Ground, ElementType.Rock), 2f },
        { (ElementType.Ground, ElementType.Ghost), 1f },
        { (ElementType.Ground, ElementType.Dragon), 1f },
        { (ElementType.Flying, ElementType.Normal), 1f },
        { (ElementType.Flying, ElementType.Fire), 1f },
        { (ElementType.Flying, ElementType.Water), 1f },
        { (ElementType.Flying, ElementType.Electric), 0.5f },
        { (ElementType.Flying, ElementType.Grass), 1f },
        { (ElementType.Flying, ElementType.Ice), 1f },
        { (ElementType.Flying, ElementType.Fighting), 1f },
        { (ElementType.Flying, ElementType.Poison), 1f },
        { (ElementType.Flying, ElementType.Ground), 1f },
        { (ElementType.Flying, ElementType.Flying), 1f },
        { (ElementType.Flying, ElementType.Psychic), 1f },
        { (ElementType.Flying, ElementType.Bug), 2f },
        { (ElementType.Flying, ElementType.Rock), 0.5f },
        { (ElementType.Flying, ElementType.Ghost), 1f },
        { (ElementType.Flying, ElementType.Dragon), 1f },
        { (ElementType.Psychic, ElementType.Normal), 1f },
        { (ElementType.Psychic, ElementType.Fire), 1f },
        { (ElementType.Psychic, ElementType.Water), 1f },
        { (ElementType.Psychic, ElementType.Electric), 1f },
        { (ElementType.Psychic, ElementType.Grass), 1f },
        { (ElementType.Psychic, ElementType.Ice), 1f },
        { (ElementType.Psychic, ElementType.Fighting), 1f },
        { (ElementType.Psychic, ElementType.Poison), 1f },
        { (ElementType.Psychic, ElementType.Ground), 1f },
        { (ElementType.Psychic, ElementType.Flying), 1f },
        { (ElementType.Psychic, ElementType.Psychic), 1f },
        { (ElementType.Psychic, ElementType.Bug), 1f },
        { (ElementType.Psychic, ElementType.Rock), 1f },
        { (ElementType.Psychic, ElementType.Ghost), 1f },
        { (ElementType.Psychic, ElementType.Dragon), 1f },
        { (ElementType.Bug, ElementType.Normal), 1f },
        { (ElementType.Bug, ElementType.Fire), 0.5f },
        { (ElementType.Bug, ElementType.Water), 1f },
        { (ElementType.Bug, ElementType.Electric), 1f },
        { (ElementType.Bug, ElementType.Grass), 2f },
        { (ElementType.Bug, ElementType.Ice), 1f },
        { (ElementType.Bug, ElementType.Fighting), 1f },
        { (ElementType.Bug, ElementType.Poison), 0.5f },
        { (ElementType.Bug, ElementType.Ground), 1f },
        { (ElementType.Bug, ElementType.Flying), 0.5f },
        { (ElementType.Bug, ElementType.Psychic), 1f },
        { (ElementType.Bug, ElementType.Bug), 1f },
        { (ElementType.Bug, ElementType.Rock), 1f },
        { (ElementType.Bug, ElementType.Ghost), 1f },
        { (ElementType.Bug, ElementType.Dragon), 1f },
        { (ElementType.Rock, ElementType.Normal), 1f },
        { (ElementType.Rock, ElementType.Fire), 1f },
        { (ElementType.Rock, ElementType.Water), 1f },
        { (ElementType.Rock, ElementType.Electric), 1f },
        { (ElementType.Rock, ElementType.Grass), 1f },
        { (ElementType.Rock, ElementType.Ice), 1f },
        { (ElementType.Rock, ElementType.Fighting), 0.5f },
        { (ElementType.Rock, ElementType.Poison), 1f },
        { (ElementType.Rock, ElementType.Ground), 1f },
        { (ElementType.Rock, ElementType.Flying), 1f },
        { (ElementType.Rock, ElementType.Psychic), 1f },
        { (ElementType.Rock, ElementType.Bug), 1f },
        { (ElementType.Rock, ElementType.Rock), 1f },
        { (ElementType.Rock, ElementType.Ghost), 1f },
        { (ElementType.Rock, ElementType.Dragon), 1f },
        { (ElementType.Ghost, ElementType.Normal), 0.5f },
        { (ElementType.Ghost, ElementType.Fire), 1f },
        { (ElementType.Ghost, ElementType.Water), 1f },
        { (ElementType.Ghost, ElementType.Electric), 1f },
        { (ElementType.Ghost, ElementType.Grass), 1f },
        { (ElementType.Ghost, ElementType.Ice), 1f },
        { (ElementType.Ghost, ElementType.Fighting), 1f },
        { (ElementType.Ghost, ElementType.Poison), 1f },
        { (ElementType.Ghost, ElementType.Ground), 1f },
        { (ElementType.Ghost, ElementType.Flying), 1f },
        { (ElementType.Ghost, ElementType.Psychic), 2f },
        { (ElementType.Ghost, ElementType.Bug), 1f },
        { (ElementType.Ghost, ElementType.Rock), 1f },
        { (ElementType.Ghost, ElementType.Ghost), 1f },
        { (ElementType.Ghost, ElementType.Dragon), 1f },
        { (ElementType.Dragon, ElementType.Normal), 1f },
        { (ElementType.Dragon, ElementType.Fire), 1f },
        { (ElementType.Dragon, ElementType.Water), 1f },
        { (ElementType.Dragon, ElementType.Electric), 1f },
        { (ElementType.Dragon, ElementType.Grass), 1f },
        { (ElementType.Dragon, ElementType.Ice), 1f },
        { (ElementType.Dragon, ElementType.Fighting), 1f },
        { (ElementType.Dragon, ElementType.Poison), 1f },
        { (ElementType.Dragon, ElementType.Ground), 1f },
        { (ElementType.Dragon, ElementType.Flying), 1f },
        { (ElementType.Dragon, ElementType.Psychic), 1f },
        { (ElementType.Dragon, ElementType.Bug), 1f },
        { (ElementType.Dragon, ElementType.Rock), 1f },
        { (ElementType.Dragon, ElementType.Ghost), 1f },
        { (ElementType.Dragon, ElementType.Dragon), 2f },

        // Add all type matchups
    };

    public static float GetEffectiveness(ElementType attack, ElementType defense)
    {
        return chart.GetValueOrDefault((attack, defense), 1f);
    }

    public static float CalculateEffectiveness(ElementType attack, List<ElementType> defenderTypes)
    {
        float totalEffectiveness = 1f;
        foreach (var defenderType in defenderTypes)
        {
            totalEffectiveness *= GetEffectiveness(attack, defenderType);
        }
        return totalEffectiveness;
    }

}
